"use client";
import "./globals.css";

import "font-awesome/css/font-awesome.min.css";
import { UserProvider } from "@/context/UserContext";
import App from "./app";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <App>{children}</App>
      </UserProvider>
    </html>
  );
}
